### PR TITLE
Move flatpages to templates

### PR DESCRIPTION
**Pull request by okaycj**
This PR is to remove existing flat pages from the our site so that they may be translated.

### CODE REVIEW

**Review by mekline — CHANGES_REQUESTED** [review]
The logic of the reorganization basically makes sense to me, but can you please demo me how the translation model works e.g. on the home.html page? 

Sonarcloud is reporting 'code smells' and a few other things, so please let me know if any of those warrant discussion/explanation.  Do you generally find you can correct all these issues, or should be discussing/documenting what happens with those it makes sense to leave?

**Comment by okaycj** [comment]
> Sonarcloud is reporting 'code smells' and a few other things, so please let me know if any of those warrant discussion/explanation. Do you generally find you can correct all these issues, or should be discussing/documenting what happens with those it makes sense to leave?

I'll fix these issues and update the PR.

**Comment by okaycj** [comment]
> The logic of the reorganization basically makes sense to me, but can you please demo me how the translation model works e.g. on the home.html page?

Sure thing!  I'll put up some images of the home page translated.

**Comment by mekline** [comment]
We can do a first pass in standup today also!

**Comment by okaycj** [comment]
This works is being done in #904.  Closing.

**Pull request closed without merging**
