### PR TITLE
Update to reviewing tab

### LINKED ISSUE #612: Add tabs for studies that are rejected or paused
# TL;DR
When navigating studies on the Experimenter interface, show tabs for "rejected" and "paused" studies as well as "active," "created," etc.

# Narrative
As an admin or study reviewer, I would like to be able to see studies that are currently approved and could be made active, as well as studies that might be resubmitted in the future. As a researcher I would like to be able to see my paused & rejected studies as well as these are "in progress."

# Acceptance Criteria

- [ ] Tabs for rejected and paused studies added to study list view

### LINKED ISSUE #863: Sorting and/or Tagging Studies in Admin Review Queue - MKS to parse out
**TL;DR**: When looking at the list of studies submitted for Admin Review (and approval/rejection), I want better ways to keep track of information regarding original date of submission, whether I have scheduled a video chat session (for synchronous external studies), etc.

**Narrative**
As an admin or study reviewer, I am losing track of which studies in the admin review queue are the highest priority for my attention. This is because we have many more studies, and the displayed information does not capture the information I need to make my decision. Two things stand out as most important: (1) I can see "Last Edited" but NOT when it was originally submitted for admin review--this means that I may think a study is low priority rather than very high priority (e.g., I think it was only submitted yesterday, when in fact it was submitted two weeks ago but the date got updated when a researcher made a trivial change to it), (2) now that we have external synchronous studies, I might schedule a live review session (e.g., on Zoom) at the researcher's earliest available time 2 weeks in the future, and now there is nothing more for me to do with it in the queue, but it will capture my attention as being "old" and demanding my attention.

**Implementation Notes**
- I think the first point (1) could be addressed by having the "Study submitted" visible in the summary view I see when looking at Manage Studies: Submitted AND having the list sortable by that field
- I think (1) is trickier and has more potential solutions, and I'm not sure how difficult different ones would be to implement. One idea that comes to mind is having a field I can toggle to indicate a live admin review session is scheduled, and then it moves to a different tab OR to the bottom of the list.

### LINKED ISSUE #991: Updates to Reviewing (Admin "Submitted Studies") tab
This is a response to #863 as well, providing some updates to make the submitted study list easier for reviewers to use!

This is the current view of Submitted studies:

Image

In the future, we will define additional rules that may impact how studies move between states, but for now we just lay some groundwork and promote hopefully more useful info now that there are so many more studies in any given category. 

The intended new content and layout for the cards is shown here:

https://docs.google.com/spreadsheets/d/17tZMghFDAwQiZ5tAUACjsN07gduclZq275H7udOfUww/edit#gid=0

Notes: 

* "Last Status Update" is identical to the date of the most recent study log
* Study "Type" list is internal, external/sync and external/async, but this list of types could change or expand in the future.
* "Approved By" will always be "Lookit Admin" at the moment, but we're setting this up to be useful for auto-approving of some studies in the future.

### PR DESCRIPTION
**Pull request by okaycj**
Updates to experimenter study list view. 

Closes #991 
Closes #863
Closes #612

### CODE REVIEW

**Comment by becky-gilbert** [comment]
@okaycj I've starting looking through the code changes, and I pulled this branch down so that I can see what the different study list views look like now. It all looks great to me so far! I've run out of time today but will finish on Monday.

**Comment by becky-gilbert** [comment]
@okaycj I pulled this branch down to test and I'm now seeing an error when I click on one of my two studies. This particular study is in the 'submitted' state. Here's the error:

study_detail_error

The error appears to be with the `declarations` key on this line:
https://github.com/lookit/lookit-api/blob/14c4b3a5d5443aabd045ed48c5a6532c1a4cb34f/exp/views/study.py#L499

This study was already in the 'approved' state, but I rejected it so that I could put it back in the 'submitted' state to see what the new 'submitted' cards look like. When I changed the state to 'submit', I saw this box:

change_status

So maybe the problem is that, unlike the initial submit form, this (re-)submit form doesn't have the declarations checkboxes and extra comments areas, so when the study detail view is requested, it's possible for the state to be 'submitted' but with no declarations key in `comments_extra`? I'll do some more investigating and update here if I figure this out.

**Comment by becky-gilbert** [comment]
Not sure if this is the best way to fix the above KeyError, but it worked for me:
```python
# if study is submitted, see if there are any declarations to display
declarations_exist = study.comments_extra.get("declarations")
if study.state == "submitted" and declarations_exist:
```
If you're happy with it then I can make the change on this branch. Or maybe a better approach is to make sure that `declarations` always exists?

**Review by mekline — APPROVED** [review]

**Comment by becky-gilbert** [comment]
@okaycj sorry, I just realized that the error I described above also occurs on the `develop` branch, so it's not related to the changes you made here. In any case, if you let me know your thoughts on how best to fix it then I'd be happy to do a separate PR for that. 
All of your study list view changes look good to me 👍

**Review by becky-gilbert — APPROVED** [review]

**Pull request merged**
