### PR TITLE
Move updates to production

### PR DESCRIPTION
**Pull request by okaycj**
This moves a couple fixes in to production.

- #1276 
- #1277
- #1279

### CODE REVIEW

**Review by becky-gilbert — APPROVED** [review]
LGTM, thanks!!

**Comment by becky-gilbert** [comment]
@okaycj ok to hold off on merging this until tomorrow? I might have some changes to make in orchestrator first.

**Comment by becky-gilbert** [comment]
@okaycj I checked orchestrator and am not ready to make any changes at this point, so merge away 🚀

**Review by mekline — APPROVED** [review]

**Comment by becky-gilbert** [comment]
@okaycj ok for me to add this change in before the production release? #1274

**Comment by okaycj** [comment]
> ok for me to add this change in before the production release? #1274

@becky-gilbert and I spoke about this and we decided to include it in another release.

**Pull request merged**
