### PR TITLE
Add js validation error message

### PR DESCRIPTION
**Pull request by okaycj**
This PR adds the error message from [js2py](https://github.com/PiotrDabkowski/Js2Py), which is the back end validator for JavaScript code.  Additionally, I removed the `^` from the version of js2py in `pyproject.toml`.  This was for no other reason then it follows the existing pattern.  

Screenshot 2023-09-06 at 11 00 22 AM

### CODE REVIEW

**Review by bleonar5 — APPROVED** [review]

**Comment by becky-gilbert** [comment]
@okaycj is it possible that this `javascript-error-message` branch was accidentally based off of your `jspsych-studytype` branch? I'm on this branch and tried creating a new study, and I get an error after going through the study ad/recruitment page, at the point when I should be directed to the EFP study details page:
> ValueError at /exp/studies/743/study-details/
> The view exp.views.study.ExperimentRunnerEditRedirect didn't return an HttpResponse object. It returned None instead. 

It looks like `ExperimentRunnerEditRedirect` was introduced on your jsPsych study type branch.

**Comment by becky-gilbert** [comment]
Ah nevermind, I see now that `ExperimentRunnerEditRedirect` was part of the latest production release. I'm not sure why I'm getting an error on the study details page when trying to create a study, but I will update here if I figure it out.

**Comment by okaycj** [comment]
@becky-gilbert 

> Ah nevermind, I see now that `ExperimentRunnerEditRedirect` was part of the latest production release. I'm not sure why I'm getting an error on the study details page when trying to create a study, but I will update here if I figure it out.

You probably need to run migrations.

**Comment by becky-gilbert** [comment]
@okaycj yep that was it 🤦‍♀️ Thanks!

**Review by becky-gilbert — APPROVED** [review]
Just tested this and it works great! 👍

**Comment by becky-gilbert** [comment]
Let's plan to merge this before the next production release (sometime next week?) when we deploy the the GARDEN changes, as well as some changes on orchestrator that I'll need to make before the release (for pipedeath-related environment variables).

**Pull request merged**
