### PR TITLE
404 error page

### LINKED ISSUE #1117: 404 - Provide a smooth experience for families that visit a nonworking link
# TL;DR

Upcoming site merge will cause any existing links to various subdomains of childrenhelpingscience.com to fail, such as: 

https://childrenhelpingscience.com/parc <- a static page
https://childrenhelpingscience.com/all-studies/toy-room <- example of a single study's page

Families might also (somehow) currently click on a nonworking lookit.mit.edu subdomain link, and the resulting experience isn't particularly helpful. 

# Narrative

As a family, if I click on a link that doesn't work for whatever reason, I want to see a friendly helpful guide to places I might want to go, like signup or viewing studies, in place of the current "Not Found" screen. 

Screen Shot 2023-02-17 at 12 09 32 PM

# New Page design

Big text: Oops! We couldn't find that page!

"Big C" logo guy, for friendliness, on white background

Smaller text: Welcome to Children Helping Science! We recently relaunched our website, which means that some links may no longer be working. To find studies you can participate in from home, please click on one of the options below:

[4 age groups with big stock photos, identical to these images and links as they appear on the front page]

Rough mockup in the slide deck: https://docs.google.com/presentation/d/1s91BnmNT-vR6RqSeadoU2wB1c-wjkNBsJjS_bg_kLSw/edit#slide=id.g23b16ee5720_0_0

# Acceptance Criteria
A precise description of how/when this issue will be considered closed, e.g.:

- [ ] Decide format & content of new "404" type page!
- [ ] Implement new page
- [ ] Testing works for a nonworking lookit.mit.edu subdomain
- [ ] Potentially leave ticket open until post CHS merger to ensure that those pages in fact wind up failing in the way we want them to

### PR DESCRIPTION
**Pull request by okaycj**
Added 404 error view.  

Screenshot 2023-05-22 at 11 40 39 AM
Screenshot 2023-05-22 at 11 40 48 AM
Screenshot 2023-05-22 at 11 43 19 AM
Screenshot 2023-05-22 at 11 43 23 AM
Screenshot 2023-05-22 at 11 43 26 AM

Closes #1117

### CODE REVIEW

**Comment by mekline** [comment]
I sent you an invite to a Canva board with the (large) images; can you add those as well?

**Review by becky-gilbert — APPROVED** [review]
One suggestion: it might look better if the image/text under the title is centered, and maybe narrower. But I'm happy to be overruled 🙂 

Also it looks like the base branch of the pull request is `age-group-filter` - is that right?

**Comment by becky-gilbert** [comment]
> One suggestion: it might look better if the image/text under the title is centered, and maybe narrower. But I'm happy to be overruled 🙂

Ah, I see now that you've done this via Melissa's mock-up, so please ignore me!

**Comment by becky-gilbert** [comment]
@okaycj 

Here's the code I have for the age group study links on the home page: https://github.com/lookit/lookit-api/blob/3670f20a41b9dfa0117ffe509fec40ef1ecc955f/web/templates/web/home.html#L98-L127

It shows the images as a 2x2 grid on larger screens and 1x4 grid on narrow screens. Feel free to use this for the bottom of the 404 page, and let me know if you have feedback!

Also FYI, the URLs used in the `<a>` tags aren't correct because I haven't merged in your PR with those views. I put a placeholder in for now and will change the links once things are merged.

**Comment by okaycj** [comment]
@becky-gilbert 

> @okaycj
> 
> Here's the code I have for the age group study links on the home page:
> 
> https://github.com/lookit/lookit-api/blob/3670f20a41b9dfa0117ffe509fec40ef1ecc955f/web/templates/web/home.html#L98-L127
> 
> It shows the images as a 2x2 grid on larger screens and 1x4 grid on narrow screens. Feel free to use this for the bottom of the 404 page, and let me know if you have feedback!

To keep the code as DRY as possible, can we drop the above html into its own file and use [include](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#include) in the template?

> 
> Also FYI, the URLs used in the `<a>` tags aren't correct because I haven't merged in your PR with those views. I put a placeholder in for now and will change the links once things are merged. Similarly, I can also replace the image file paths on the 404 page later when the two branches are merged, if you want to use placeholder image paths for now.

The PR with those filter views has now been merged into develop.

**Comment by mekline** [comment]
I like Becky's suggestion to narrow the text, so it matches the width of the funding blurb at the bottom, or the width of the age group photos - somewhere around there, whatever width is most reasonably to tie it to.

**Review by mekline — CHANGES_REQUESTED** [review]
(see comment!)

**Comment by becky-gilbert** [comment]
@okaycj 

> To keep the code as DRY as possible, can we drop the above html into its own file and use [include](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#include) in the template?

Yes! I can't believe I didn't think of that 🤦‍♀️ I've updated the `chs-homepage` branch so that the HTML for the age-group images/links is now in a separate file that can be included (see https://github.com/lookit/lookit-api/pull/1200/commits/8153381b7d1e095dce1ece484c33824f52eee261).

> The PR with those filter views has now been merged into develop.

Got them now, thanks!

**Comment by becky-gilbert** [comment]
@okaycj @mekline I merged the develop branch into this one so that I could add in the studies-by-age-group images. Here's what it looks like now:

Screenshot 2023-05-19 at 2 07 18 PM

I also took a stab at centering the logo with the title and aligning the text with the images. Here's what I came up with:

Desktop/laptop:

Screenshot 2023-05-19 at 2 26 49 PM

Mobile: 

Screenshot 2023-05-19 at 2 24 02 PM

If you like this, let me know and I'll push the changes to this branch.

**Comment by mekline** [comment]
Great, love the centered image & larger text!

**Comment by okaycj** [comment]
@becky-gilbert 

> If you like this, let me know and I'll push the changes to this branch.

Sorry about this.  I had already done the merge and work.  I ended up merging my changes.

**Pull request merged**
