### PR TITLE
Lab images

### LINKED ISSUE #918: Customized header images and text for lab pages
# TL;DR
Allow each lab to upload lab logos, and specify text that they want to appear under the logo and above the list of studies from the lab.

# Narrative
As a researcher, I want a more attractive lab 'landing page' that is customized to show my lab's logo above the studies (in combination with #1024, which lets them custom-order the studies that appear!)

# Acceptance Criteria

See screenshot mockup at the bottom

## Lab Edit View

We will divide the current form into two visual chunks - Lab info, and Lab page design.  The final order of the fields on this page should be: 

Lab Name
Institution
PI Name
Contact Email
Contact Phone
Lab Website
IRB Contact Website
[a line/visual separator]
Custom URL
Banner Image
Badge/Small Image
Lab Description

### Specific changes

[ ] Question - there is already a Lab Description field provided, but I can't find any Lookit URLs where this text would appear to a family.  I propose we reuse this for the lab text!

DB field: (existing) 'description'
Field title: Status quo
Field content: Status quo (but see implementation notes!)
Help text: "A short (2-3 sentences), parent-facing description of what your lab studies or other information of interest to families. This will be displayed at your custom URL."

[ ] New field for a banner image

Database field on the studies_lab object: 'lab_banner_image'

Title: Lab Banner Image

 Help text: "This is the banner image that participants will see at the top of the screen, above your description. Please keep your file size less than 1 MB. Banner images will be displayed in a [TBD] aspect ratio (a long, skinny rectangle)."

[ ] New field for a 'badge' image

Database field on the studies_lab object: 'lab_badge_image'
Title: Lab Badge Image
"This is a small image that will be used as an icon or badge, including for mobile views of your custom lab URL. Badge images will be displayed in a square aspect ratio."

# Implementation Notes

- Make sure to check that lab pages render well on small-width browser.  Possibly use the "Lab Badge" image in place of the lab banner for mobile/small widths?
- Make sure to check that lab description text looks reasonable, including if labs provide e.g. multiple paragraphs, a bulleted list
- At first, most labs will have a description, but *not* yet an image, so we should make sure that this is a state that looks reasonable.  Potentially display the lab's name in large font instead if a banner image is not provided? 

## Mockups

Note from standup: Remember that there are three edge conditions to consider: A lab provides neither banner nor badge images; lab provides only banner; lab provides only badge. All of these should look at least "reasonably okay" on a lab page.

### Laptop/wider window

* If a banner image is provided, show it!
* If no images are provided, display the lab's name in large font
* If a badge but no banner is provided, display the badge on the left next to the lab's name

Current:

Image

Desired:

Image

### Mobile/narrow

* If no badge image is provided, show the lab's name in medium sized font (e.g. the same as the "Manage Studies" and similar page titles) at full width. Place the description text underneath, also at full width. 
* If a badge image is provided, show it on the left side. Place the lab name and description text to the right of that square image. (Note this is a bit different to the mockup I showed you in standup @okaycj !)

Current: 

Image

Desired (Though ideally the lab name would shrink in font to fit a single line, if possible): 

Image

- Ideally, also fix the padding of the home button in the top bar, and deal with how study images are displayed! (See #1038)

### PR DESCRIPTION
**Pull request by okaycj**
This PR adds the ability for labs to add a banner and badge image to their customized lab page.  The images are validated.  The badge image must be square and the banner ratio must be above 2.  

Additionally, the lab's description field's help text was updated. 

Closes #918

Screenshot 2023-01-20 at 4 27 21 PM
Screenshot 2023-01-20 at 1 29 52 PM
Screenshot 2023-01-20 at 1 30 04 PM
Screenshot 2023-01-20 at 1 30 15 PM

### CODE REVIEW

**Comment by mekline** [comment]
Thanks!  Can you please make new issues for the "TODO" steps if you're not completing them this sprint? 

Or if you have time, here is a revision for these fields:

Banner Image: This image will be shown at the top of your custom URL page, when it is viewed on a laptop/wide browser window. Please keep your file size less than 1 MB.


Badge Image: This image will be shown at the top of your custom URL page when it is viewed on a mobile device/narrow browser window, and as a badge/avatar image for your lab. This image should be square. Please keep your file size less than 1 MB.

And here are a couple more things, ideal to implement now if time, otherwise please make new issues:

- Should we validate the shapes, as with the study images?  For the banner, we could specify a range like between 1:7 and 1:3. 
- To make thing flow more smoothly it would be great if you could move these two items to immediately after the custom-url box.
- Amendment to the help text for the "Description" field: "A short (2-3 sentences), parent-facing description of what your lab studies or other information of interest to families. This description will be shown under the banner image on your custom URL page."

**Comment by okaycj** [comment]
@mekline 

> * Should we validate the shapes, as with the study images?  For the banner, we could specify a range like between 1:7 and 1:3.

The new image fields are validated.  The badge image needs to be square and the banner image is validated to be above a ratio of 2 (w:h).  Of course, let me know if you'd like different behavior.  

> * To make thing flow more smoothly it would be great if you could move these two items to immediately after the custom-url box.
> * Amendment to the help text for the "Description" field: "A short (2-3 sentences), parent-facing description of what your lab studies or other information of interest to families. This description will be shown under the banner image on your custom URL page."

I added commits for these two points.  Thank you for the feedback.

**Comment by mekline** [comment]
Okay, that all sounds good!!

**Comment by becky-gilbert** [comment]
@okaycj @mekline I know this has been merged but I have a few questions about things I noticed while updating the documentation. 

I added banner and badge images to the demo lab on staging in order to get some screenshots, and I noticed two things:
1. **When the banner image is shown, I don't see the lab name on the page.** E.g. "Sandbox Lab" is shown on the 3rd and 4th screenshots from CJ's post above but not on the 2nd. Is that intentional? If not, let me know and I can try to add it.
2. Based on the help text in [Melissa's comment](https://github.com/lookit/lookit-api/pull/1064#issuecomment-1398878965), I expected the lab page to show the banner image on wide browser windows and badge image on narrow windows. **But when the lab has both image types, I only see the banner image.** I don't see the badge image on the lab page, even when I navigate to the page from a narrow window or emulate mobile (screenshot below). I do see the badge image on the lab page after I've cleared the lab's banner image. 

WRT to question 2 - if it would be helpful, I can either (a) try to implement the functionality that I was expecting, i.e. banner on wide browser and badge on narrow/mobile (but might take a while to figure out), or (b) edit the form's help text to say that the badge image will be shown on the lab page if there is no banner image (faster).

Here's a screenshot of the demo lab page on staging, from a desktop browser using the mobile emulator. Note that this page shows the banner rather than badge image, and there's no 'Demo Lab' title.

staging_lab_page_mobile

**Comment by becky-gilbert** [comment]
Answers to my questions after talking to Melissa and CJ:
1. This is intentional. The idea is that the lab will probably have a banner image that includes their lab name. I'll add a note in the docs about this. (At some point in the future we may decide to add the lab name to the page text as well.)
2. The images should switch based on browser window dimensions but we're not going to implement that in this shape - it'll be part of our mobile compatibility/responsiveness work. I'll make a note in the docs about how this works now, and we can change it later once we get the image types to display as intended.

**Pull request merged**
