### PR TITLE
Deploy to production

### PR DESCRIPTION
**Pull request by okaycj**
This production deploy will cover the following changes:

Copy changes: 
- #1048
- #1067 

Study Features: 
- #1041 
- #1047 
- #1063 
- #1044

Lab Features:
- #1064

Bug fixes: 
- #1042 
- #1053 
- #1049 
- #1054

Dependabot:
- #1028
- #1032 
- #974 
- #1046

### CODE REVIEW

**Review by becky-gilbert — APPROVED** [review]
This all looks great! 🚀 
I think we still need docs for:
- #1064 
- #1047 (docs issue: https://github.com/lookit/lookit-docs/issues/278)

I'll do a first draft of these and create PRs in the docs repo today.

**Comment by mekline** [comment]
Thank you @becky-gilbert !!

**Review by mekline — CHANGES_REQUESTED** [review]
Arg - a small (I hope) change request on the study prereqs item, the rest of the UI changes look great. 

The issue: (1) If I accidentally click on a study to add to the list, I can't see how to UN click it.  Should there be a blank/empty space at the top that corresponds to "no study chose"?

A related issue, which can be punted to a later issue, is that it's a bit hard to see which studies I've currently chosen.  If it wasn't hard to do now, it would be nice if they were listed outside of the selection box.  E.G. 

# Must have participated
[Selection Box]
Participants must have participated in: 
- First selected
- Second selected, etc. 
- 
# Must not have participated
[Selection Box]
Participants must NOT have participated in: 
- First selected
- Second selected, etc. 

But let's skip the latter to a later issue probably!

**Comment by okaycj** [comment]
@mekline

The above described issues are addressed in #1076.

**Comment by mekline** [comment]
(I change my review from "changes requested" to "approved", will keep an eye out in case i get notifications to say that officially :))

**Pull request merged**
