### PR TITLE
Merge Develop into Master

### LINKED ISSUE #123: Allow families to see their videos, & add some additional details to past studies
*Pain Point*: Once parents participate in a study, there is no immediate confirmation that it "worked" and Lookit has their data, or any later confirmation that it has been used to do cool science. They also do not have automatic access to their own data, although they often want to see their videos; instead, a researcher has to provide it if desired, which is labor-intensive and introduces unnecessary possibilities for human error (e.g. sending the wrong child's video). 

*Acceptance Criteria*:  
- Parents can download any video clips from a session from the "Past Studies" view when logged in. (Nice but not required if they can actually just see the clips embedded in the browser.)
- Parents can see some basic information about past study sessions, including which child participated, status of consent coding (yes/no/pending/no video(?)), research group PI/contact.
- Parents should *not* see sessions with completedConsentFrame=false displayed
- Parents can see the "status" of a study that they participated in, as provided by the researchers - e.g., data collection, analysis, writing up results, here's a link to the paper/media article/etc.

*Implementation notes/Suggestions*: 
- We've discussed adding a freeform string field to the study model, editable by researchers in the study edit view, representing the current state of the study.
- Eventually (not as part of this ticket) parents might also be able to (going forward) view any study debriefing text from "Past Studies," since this may contain individual results or condition info. Having set up an "exit survey" frame type to support withdrawal of video will make this easier, in that we'd be able to see if there's a frame of type exit-survey in the expData for this response, and if so, fetch its debriefing text. 
- Eventually (not as part of this ticket) parents might also be able to view/download the consent form text. This is now stored as part of the consent form in expData.

### LINKED ISSUE #138: Tool to upload feedback and other manually researcher-generated session data
*Pain point*: Currently researchers need to use the API to leave feedback to parents about particular sessions. Feedback is one of the better ways we have to build engagement (let parents know a human watches & appreciates their video!) and we want it to be easy for researchers to leave. 

*Acceptance criteria*: 
* Without using the API directly, researchers can provide feedback per session that is associated with session data and (as it is now) accessible to the family. (This should indeed be stored as part of the response, *not* emailed.)  
- Ideally this *can* be done via file upload, even if there is also a nice interface for it, so as not to stand in the way of whatever analysis processes individual labs develop.
* Ideally, researchers can upload arbitrary text data that is stored with/linked to the session data, e.g. a manual "score" for the first part of a longitudinal study that is used by the second session to generate appropriate stimuli. 

*Implementation notes/Suggestions*: 

- Feedback is currently implemented sort of like consent rulings, as a separate model; there can be multiple feedbacks for the same response, perhaps left by different researchers. This is fine but if it complicates things, condensing down to a single string feedback field on the response or making it so there is at most one feedback associated with a response would also work fine. (Migrations would be a little annoying but could just join together multiple feedbacks if needed without messing up any existing .)

- MIT is the only group currently using the feedback API, but we do use it and will need to update code to accommodate changes (see https://github.com/kimberscott/lookit-data-processing/blob/coding-workflow-multilab/scripts/experimenter.py) 

- Feedback would ideally be possible to add/edit via the consent manager, "individual responses" view, and by uploading a copy of the study CSV they downloaded with a "feedback" column updated. It should be possible to add feedback on sessions where the consent ruling is 'rejected' or 'pending.' 

- The arbitrary data should be cleaned to protect the database, and multiple attributes can be stored in a single standard JSON field if that's helpful. This could also be somehow joined with the "feedback" model if easier, e.g. have a "researcher-generated session data" model that's associated with a session and includes feedback and also this other data.

### LINKED ISSUE #141: Add checkboxes for various conditions/circumstances for children & families, in child & demographic surveys.
*Pain point*: Many researchers are interested in working with specific populations, but families do not have a standardized way to indicate whether they fall into various groups in a way that would support use of this information for recruitment/eligibility.

*Acceptance criteria*: 
* In the child and demographic forms, parents can indicate things that apply to the child/family (yes/no or checkboxes), from a standard list + "other." E.g., autism, Down syndrome, Williams syndrome, perinatal stroke, vision/hearing impairments, twin, multilingual. [Kim to provide an initial list.] 
* Researchers can use these fields in their study eligibility criteria - e.g., this study is for 4- to 6-month olds who were born before 37 weeks and are being raised in multilingual households. 
* Researchers can use presence/absence of a *sibling* with various criteria in study eligibility. E.g., this study is for 1- to 3-year olds with a sibling who is at least 6 years old, or for children with at least 3 siblings total, or for children without any younger siblings, or for 8- to 11-month-olds with a sibling with autism. (The last form is in fact the primary concrete motivation for this capacity, but being able to use presence of a sibling with an arbitrary condition and/or presence/absence of siblings will be useful to other researchers in the future.) 

*Implementation notes/Suggestions*: MIT OGC advises us that including medically-relevant options  is fine from a legal standpoint (MIT is not a covered entity under HIPAA).

### PR DESCRIPTION
**Pull request by Datamance**
This is a big Kahuna!

Fixes #138 
Fixes #123 
Fixes #141 

-- each of the above referenced issues should be closed out after this merge.

### CODE REVIEW

**Comment by kimberscott** [comment]
Could we link to the docs (https://lookit.readthedocs.io/en/develop/researchers-set-study-fields.html#criteria-expression) in the study edit form here?
Screen Shot 2019-08-20 at 2 44 10 PM

**Comment by kimberscott** [comment]
Could we also indicate in the save study warning that changes to the eligibility criteria do not auto-reject the study (like toggling discoverability)?
Screen Shot 2019-08-20 at 2 45 54 PM

**Comment by kimberscott** [comment]
On staging I'm currently only ever able to see a single video clip in the "past studies" view, even when there are multiple accessible by the experimenter, do you see the same behavior?

**Comment by kimberscott** [comment]
And could we put a little indicator in the "-> Next video" button (or elsewhere nearby) on the "Past studies" view that says which video it is, like "[Video 2 of 5] -> Next video"

**Comment by Datamance** [comment]
```On staging I'm currently only ever able to see a single video clip in the "past studies" view``` --> probably an artifact of the video being small and not being able to see the index of the given video. Addressing this in the changelist.

**Comment by Datamance** [comment]
> Could we link to the docs (https://lookit.readthedocs.io/en/develop/researchers-set-study-fields.html#criteria-expression) in the study edit form here?
> Screen Shot 2019-08-20 at 2 44 10 PM

👍

**Comment by kimberscott** [comment]
On staging I'm no longer seeing the age-based warnings when I try to participate with a child outside the age range for a study, although I do see the warning based on the criteria expression.

**Comment by kimberscott** [comment]
Also, it's no longer possible to select "Not sure or prefer not to answer" on gestational age at birth in the child form - can we add a true "blank" in place of that like for the gender dropdown?

**Pull request merged**
