### PR TITLE
Bootstrap 5 scientists

### PR DESCRIPTION
**Pull request by okaycj**
Edits to the Scientists view

Screenshot 2023-02-14 at 11 26 23 AM
Screenshot 2023-02-14 at 11 26 27 AM
Screenshot 2023-02-14 at 11 26 31 AM
Screenshot 2023-02-14 at 11 26 34 AM
Screenshot 2023-02-14 at 11 26 37 AM
Screenshot 2023-02-14 at 11 26 42 AM
Screenshot 2023-02-14 at 11 26 45 AM

### CODE REVIEW

**Comment by mekline** [comment]
Great - I'm happy to say I'm not adding any new CSS thoughts to my current mental list!  But, this needs a picture & blurb for @becky-gilbert !!  Becky, can you provide a pic/blurb?  If you check out the full set of photos you can see that the 'standard' pic used to be an "action shot" with a kid/pet so you're welcome to do the same if you like!

**Comment by mekline** [comment]
Actually @okaycj could you swap in an action shot for me as well? 

PXL_20220108_161159930

**Comment by becky-gilbert** [comment]
>  this needs a picture & blurb for @becky-gilbert !! Becky, can you provide a pic/blurb?

Will do! @okaycj do you care whether I add myself to the `bootstrap-5-scientists` branch, or `develop`, or a separate branch..?

**Review by mekline — CHANGES_REQUESTED** [review]
(I requested changes in the comments, just realized I didn't actually submit the review!)

**Comment by becky-gilbert** [comment]
This all looks great to me!
Updated this branch with new MKS pic and my pic/bio:
Screenshot 2023-02-17 at 4 42 52 PM

@okaycj I'm happy to resolve the merge conflicts and merge this, unless you'd rather handle the conflicts yourself?

**Review by becky-gilbert — APPROVED** [review]

**Review by mekline — CHANGES_REQUESTED** [review]
Just one change - upon reflection, both before and with your new edits, the four/five of us are in a totally arbitrary order.  I think of it as being alphabetical, but that's not actually true.  Let's make it alphabetical by last name! Gilbert, Green, Kline Struhl, Schulz, Sheskin.

**Comment by becky-gilbert** [comment]
> Let's make it alphabetical by last name!

Done!

**Review by mekline — APPROVED** [review]

**Pull request merged**
